### ISSUE TITLE
Location and Desired Location do not renrender

### ISSUE THREAD

**Issue by seang549** [gschool-blue-ocean/learnlaunchnexus#62]
Describe the bug
Dashboard component does not rerender when you change the location or desired location even though a useEffect is used
To Reproduce
a working product that will rerender the location and desire location upon change

Expected behavior
useEffect reruns the async function and changes only the location and/or desired location

Priority
Medium priority

Screenshots/Video
![image](https://github.com/gschool-blue-ocean/learnlaunchnexus/assets/128072204/186d0836-ece0-4fb3-ad62-22b0254d92d6)
Desktop
OS: MAC
Browser: Google
Additional context
N/A

**Comment by BenjaminSchenk** [comment]
Pedro and I fixed it by using a useState with a Boolean so every time you hit the close button it changes the state and that state is in the dashboard component. Which causes it to rerender that component solving the issue.
