### ISSUE TITLE
OHH-45 Visual glitches upon changing of location

### ISSUE THREAD

**Issue by seang549** [gschool-blue-ocean/learnlaunchnexus#69]
Describe the bug
For some changing locations makes the UI "freak out" and pop in and out.

To Reproduce
Determine if it is an issue or on a specific brower

Expected behavior
A smooth transition between each location change

Priority
High priority

Desktop
Mac
Browser: Google

Additional context
N/A

**Comment by joelaspe** [comment]
Tested in multiple browsers, cannot duplicate. Closing
