### ISSUE TITLE
0HH-46 Todo list takes a while to render when no cohort is selected

### ISSUE THREAD

**Issue by seang549** [gschool-blue-ocean/learnlaunchnexus#70]
Describe the bug
Load time is long

To Reproduce
Consider lazy loading or settimeout with loading component 

Expected behavior
Todo list to appear upon login

Priority
Medium priority

Desktop
Mac
Browser: Google

Additional context
N/A

**Comment by joelaspe** [comment]
Appears to not be an issue anymore

**Comment by joelaspe** [comment]
Closing after testing
