### ISSUE TITLE
OHH-53 Casing is not handled for Email on login

### ISSUE THREAD

**Issue by pedrovily1** [gschool-blue-ocean/learnlaunchnexus#71]
Describe the bug
Login form will not login user if you use different casing.  

To Reproduce
to reproduce here is an example test@test.com - OK TeSt@TEST.com - Wont work.

Expected behavior
explained above

Priority
Medium priority

Desktop
Mac
Browser: Google

Additional context
N/A

**Comment by joelaspe** [comment]
Fixed
