### ISSUE TITLE
OHH-52 changing a cohort does not take you back to the table view

### ISSUE THREAD

**Issue by pedrovily1** [gschool-blue-ocean/learnlaunchnexus#74]
Describe the bug
When you change the the "Select a cohort" dropdown while look at a single student, the cohort table is not rendered.

To Reproduce

Select a cohort - Select a student - try to change cohort from dropdown

Expected behavior

Cohort table will not be re-rendered

Priority
Medium priority

Desktop
Mac
Browser: Google

Additional context
N/A

**Comment by joelaspe** [comment]
I think this was partially fixed, but there is another bug where selecting cohort 1 initially will not load.

**Comment by joelaspe** [comment]
Ben reports this was fixed, expect to see in next pull request
